package com.example.dynamicitemlazycolumn


val payloadOne = """
{
   "listItems":[
      {
         "type":"ROW",
         "listItems":[
            {
               "type":"IMAGE",
               "message":"Hello Here",
               "backgroundColor": "GREEN"
            },
            {
               "type":"IMAGE",
               "message":"Thank You!!",
               "backgroundColor": "RED"
            }
         ]
      }
   ]
}
""".trimIndent()

val payloadMany = """
{
   "listItems":[
      {
         "type":"TEXT",
         "message":"Dyno Text",
         "textAlign":"CENTER",
         "textFont":"DEFAULT",
         "alignment":"CENTER",
         "weight":0.0
      },
      {
         "type":"TEXT",
         "message":"Dyno Text",
         "textAlign":"CENTER",
         "textFont":"DEFAULT",
         "alignment":"START",
         "weight":0.0
      },
      {
         "type":"TEXT",
         "message":"Dyno Text",
         "textAlign":"CENTER",
         "textFont":"DEFAULT",
         "alignment":"END",
         "weight":0.0
      },
      {
         "type":"BUTTON",
         "message":"Dyno Button",
         "alignment":"CENTER",
         "weight":0.0
      },
      {
         "type":"BUTTON",
         "message":"Dyno Button",
         "alignment":"START",
         "weight":0.0
      },
      {
         "type":"BUTTON",
         "message":"Dyno Button",
         "alignment":"END",
         "weight":0.0
      },
      {
         "type":"IMAGE",
         "imageAlign":"CENTER",
         "alignment":"CENTER",
         "weight":0.0
      },
      {
         "type":"IMAGE",
         "imageAlign":"CENTER",
         "alignment":"START",
         "weight":0.0
      },
      {
         "type":"IMAGE",
         "imageAlign":"CENTER",
         "alignment":"END",
         "weight":0.0
      },
      {
         "type":"COLUMN",
         "listItems":[
            {
               "type":"TEXT",
               "message":"Column Dyno Text",
               "textAlign":"CENTER",
               "textFont":"DEFAULT",
               "alignment":"CENTER",
               "weight":0.0
            },
            {
               "type":"IMAGE",
               "imageAlign":"CENTER",
               "alignment":"CENTER",
               "weight":0.0
            }
         ],
         "alignment":"CENTER",
         "weight":0.0
      },
      {
         "type":"COLUMN",
         "listItems":[
            {
               "type":"TEXT",
               "message":"Column Dyno Text Start",
               "textAlign":"CENTER",
               "textFont":"DEFAULT",
               "alignment":"START",
               "weight":0.0
            },
            {
               "type":"IMAGE",
               "imageAlign":"CENTER",
               "alignment":"CENTER",
               "weight":0.0
            },
            {
               "type":"TEXT",
               "message":"Column Dyno Text End",
               "textAlign":"CENTER",
               "textFont":"DEFAULT",
               "alignment":"END",
               "weight":0.0
            }
         ],
         "alignment":"FILL",
         "weight":0.0
      },
      {
         "type":"ROW",
         "listItems":[
            {
               "type":"TEXT",
               "message":"Hello Dyno Text",
               "textAlign":"CENTER",
               "textFont":"DEFAULT",
               "alignment":"CENTER",
               "weight":1.0
            },
            {
               "type":"IMAGE",
               "imageAlign":"CENTER",
               "alignment":"CENTER",
               "weight":1.0
            }
         ],
         "alignment":"CENTER",
         "weight":0.0
      },
      {
         "type":"ROW",
         "listItems":[
            {
               "type":"TEXT",
               "message":"Hello Dyno Text",
               "textAlign":"START",
               "textFont":"DEFAULT",
               "alignment":"CENTER",
               "weight":1.0
            },
            {
               "type":"IMAGE",
               "imageAlign":"END",
               "alignment":"CENTER",
               "weight":1.0
            }
         ],
         "alignment":"CENTER",
         "weight":0.0
      },
      {
         "type":"ROW",
         "listItems":[
            {
               "type":"TEXT",
               "message":"Hello Dyno Text",
               "textAlign":"END",
               "textFont":"DEFAULT",
               "alignment":"CENTER",
               "weight":1.0
            },
            {
               "type":"IMAGE",
               "imageAlign":"START",
               "alignment":"CENTER",
               "weight":1.0
            }
         ],
         "alignment":"CENTER",
         "weight":0.0
      },
      {
         "type":"ROW",
         "listItems":[
            {
               "type":"TEXT",
               "message":"Row Start",
               "textAlign":"START",
               "textFont":"SMALL",
               "alignment":"CENTER",
               "weight":1.0
            },
            {
               "type":"IMAGE",
               "imageAlign":"CENTER",
               "alignment":"CENTER",
               "weight":1.0
            },
            {
               "type":"TEXT",
               "message":"Row End",
               "textAlign":"END",
               "textFont":"DEFAULT",
               "alignment":"CENTER",
               "weight":1.0
            }
         ],
         "alignment":"CENTER",
         "weight":0.0
      },
      {
         "type":"COLUMN",
         "listItems":[
            {
               "type":"ROW",
               "listItems":[
                  {
                     "type":"TEXT",
                     "message":"Row Dyno Text",
                     "textAlign":"CENTER",
                     "textFont":"DEFAULT",
                     "alignment":"CENTER",
                     "weight":0.0
                  },
                  {
                     "type":"IMAGE",
                     "imageAlign":"CENTER",
                     "alignment":"CENTER",
                     "weight":0.0
                  }
               ],
               "alignment":"CENTER",
               "weight":0.0
            },
            {
               "type":"IMAGE",
               "imageAlign":"CENTER",
               "alignment":"CENTER",
               "weight":0.0
            }
         ],
         "alignment":"CENTER",
         "weight":0.0
      },
      {
         "type":"COLUMN",
         "listItems":[
            {
               "type":"IMAGE",
               "imageAlign":"CENTER",
               "alignment":"CENTER",
               "weight":0.0
            },
            {
               "type":"ROW",
               "listItems":[
                  {
                     "type":"TEXT",
                     "message":"Row Dyno Text",
                     "textAlign":"CENTER",
                     "textFont":"DEFAULT",
                     "alignment":"CENTER",
                     "weight":0.0
                  },
                  {
                     "type":"IMAGE",
                     "imageAlign":"CENTER",
                     "alignment":"END",
                     "weight":0.0
                  }
               ],
               "alignment":"CENTER",
               "weight":0.0
            }
         ],
         "alignment":"CENTER",
         "weight":0.0
      },
      {
         "type":"ROW",
         "listItems":[
            {
               "type":"TEXT",
               "message":"Row Dyno Text",
               "textAlign":"CENTER",
               "textFont":"DEFAULT",
               "alignment":"CENTER",
               "weight":1.0
            },
            {
               "type":"COLUMN",
               "listItems":[
                  {
                     "type":"TEXT",
                     "message":"Column Dyno Text",
                     "textAlign":"CENTER",
                     "textFont":"DEFAULT",
                     "alignment":"CENTER",
                     "weight":0.0
                  },
                  {
                     "type":"IMAGE",
                     "imageAlign":"CENTER",
                     "alignment":"END",
                     "weight":0.0
                  }
               ],
               "alignment":"CENTER",
               "weight":1.0
            }
         ],
         "alignment":"CENTER",
         "weight":0.0
      },
      {
         "type":"ROW",
         "listItems":[
            {
               "type":"COLUMN",
               "listItems":[
                  {
                     "type":"TEXT",
                     "message":"Column Dyno Text",
                     "textAlign":"CENTER",
                     "textFont":"DEFAULT",
                     "alignment":"CENTER",
                     "weight":0.0
                  },
                  {
                     "type":"IMAGE",
                     "imageAlign":"CENTER",
                     "alignment":"CENTER",
                     "weight":0.0
                  }
               ],
               "alignment":"CENTER",
               "weight":0.0
            },
            {
               "type":"TEXT",
               "message":"Row Dyno Text",
               "textAlign":"CENTER",
               "textFont":"DEFAULT",
               "alignment":"CENTER",
               "weight":0.0
            }
         ],
         "alignment":"CENTER",
         "weight":0.0
      },
     {
         "type":"ROW",
         "listItems":[
            {
               "type":"COLUMN",
               "listItems":[
                  {
                     "type":"TEXT",
                     "message":"Contact Agent",
                     "textAlign":"CENTER",
                     "textFont":"HUGE",
                     "alignment":"START",
                     "weight":0.0
                  },
                  {
                     "type":"TEXT",
                     "message":"15/125-129 Hawthorn Road\nForest Hill 3131\nVic",
                     "textAlign":"START",
                     "textFont":"DEFAULT",
                     "alignment":"START",
                     "weight":0.0
                  }
               ],
               "alignment":"FILL",
               "weight":1.0
            },
            {
               "type":"IMAGE",
               "imageAlign":"CENTER",
               "alignment":"END",
               "weight":0.0
            }
         ],
         "alignment":"CENTER",
         "weight":0.0
      },
      {
         "type":"ROW",
         "listItems":[
            {
               "type":"IMAGE",
               "imageAlign":"CENTER",
               "alignment":"END",
               "weight":0.0
            },
            {
               "type":"COLUMN",
               "listItems":[
                  {
                     "type":"TEXT",
                     "message":"Contact Agent",
                     "textAlign":"CENTER",
                     "textFont":"HUGE",
                     "alignment":"START",
                     "weight":0.0
                  },
                  {
                     "type":"TEXT",
                     "message":"15/125-129 Hawthorn Road\nForest Hill 3131\nVic",
                     "textAlign":"START",
                     "textFont":"DEFAULT",
                     "alignment":"START",
                     "weight":0.0
                  }
               ],
               "alignment":"FILL",
               "weight":1.0
            }
         ],
         "alignment":"CENTER",
         "weight":0.0
      },
      {
         "type":"ROW",
         "listItems":[
            {
               "type":"IMAGE",
               "imageAlign":"CENTER",
               "alignment":"END",
               "weight":0.0
            },
            {
               "type":"COLUMN",
               "listItems":[
                  {
                     "type":"TEXT",
                     "message":"Contact Agent",
                     "textAlign":"CENTER",
                     "textFont":"HUGE",
                     "alignment":"CENTER",
                     "weight":0.0
                  },
                  {
                     "type":"TEXT",
                     "message":"15/125-129 Hawthorn Road\nForest Hill 3131\nVic",
                     "textAlign":"CENTER",
                     "textFont":"DEFAULT",
                     "alignment":"CENTER",
                     "weight":0.0
                  }
               ],
               "alignment":"FILL",
               "weight":1.0
            }
         ],
         "alignment":"CENTER",
         "weight":0.0
      }      
   ]
}    
""".trimIndent()